<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day033sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: COUNT () with WHERE

In [6]:
#1 Count the total number of customers.
run_sql("""SELECT COUNT(*) AS total_customers
FROM customers;""")

   total_customers
0               40

In [7]:
#2 Count how many products belong to the Electrnics category.
run_sql("""SELECT COUNT(*) AS electronics_products
FROM products
WHERE category = 'Electronics';""")

   electronics_products
0                     0

In [13]:
#3 Count how many employees work in the Sales department using the department_id.
run_sql("""SELECT COUNT(*) AS sales_employees
FROM employees
WHERE department_id = (
   SELECT department_id
   FROM departments
   WHERE department_name = 'Sales'
   );""")

   sales_employees
0                3

In [10]:
#4 Count the number of orders placed where the quantity is greater than 3.
run_sql("""SELECT COUNT(*) AS orders_quantity_greater_than_3
FROM orders
WHERE quantity > 3;""")

   orders_quantity_greater_than_3
0                              39

In [11]:
#5 Count how many employees earn a salary greater than 60000.
run_sql("""SELECT COUNT(*) AS employees_salary_greater_than_60000
FROM employees
WHERE salary > 60000;""")

   employees_salary_greater_than_60000
0                                   19

In [12]:
# Bonus Challege
run_sql("""SELECT COUNT(*) AS matching_customers
FROM customers
WHERE city IN (
    SELECT city
    FROM employees
    );""")

   matching_customers
0                  40