<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day023sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [6]:
# Topic: Sorting data using multiple columns with ORDER BY.

In [7]:
#1
run_sql("""SELECT first_name, last_name
FROM employees
ORDER BY first_name ASC, last_name ASC;""")

   first_name last_name
0       Aarav     Patel
1      Aditya       Das
2        Amit       Roy
3      Ananya     Singh
4       Arjun    Taylor
5       Aryan       Das
6      Daniel       Roy
7       David     Singh
8        Emma     Kumar
9       Grace     Brown
10       Isha       Roy
11       John     Brown
12      Kabir    Sharma
13      Karan    Taylor
14       Liam     Singh
15      Meera     Singh
16       Neha    Taylor
17      Nisha    Sharma
18       Noah     Singh
19     Olivia       Roy
20      Pooja    Sharma
21      Priya       Das
22      Rahul       Roy
23       Riya       Das
24      Rohan     Singh
25       Sara    Taylor
26      Sneha    Sharma
27     Sophia       Roy
28     Vikram       Roy
29     Vivaan     Patel

In [8]:
#2
run_sql("""SELECT *
FROM products
ORDER BY CATEGORY ASC, product_name ASC;""")

    product_id        product_name    category    price  stock_quantity
0           25      Camera Model 1      Camera  46499.0               0
1            9  Headphones Model 1  Headphones   5499.0              80
2           10  Headphones Model 2  Headphones   5999.0               0
3           11  Headphones Model 3  Headphones   6499.0              80
4           12  Headphones Model 4  Headphones   6999.0               5
5           17    Keyboard Model 1    Keyboard   2499.0              80
6           18    Keyboard Model 2    Keyboard   2999.0              35
7           19    Keyboard Model 3    Keyboard   3499.0               5
8           20    Keyboard Model 4    Keyboard   3999.0              50
9            1      Laptop Model 1      Laptop  90499.0              35
10           2      Laptop Model 2      Laptop  90999.0               0
11           3      Laptop Model 3      Laptop  91499.0              50
12           4      Laptop Model 4      Laptop  91999.0               5
13           5      Mobile Model 1      Mobile  30499.0              35
14           6      Mobile Model 2      Mobile  30999.0               0
15           7      Mobile Model 3      Mobile  31499.0              12
16           8      Mobile Model 4      Mobile  31999.0               0
17          13     Monitor Model 1     Monitor  16499.0              20
18          14     Monitor Model 2     Monitor  16999.0               0
19          15     Monitor Model 3     Monitor  17499.0               5
20          16     Monitor Model 4     Monitor  17999.0              20
21          21       Mouse Model 1       Mouse   1499.0               0
22          22       Mouse Model 2       Mouse   1999.0              20
23          23       Mouse Model 3       Mouse   2499.0              35
24          24       Mouse Model 4       Mouse   2999.0               0

In [11]:
#3
run_sql("""SELECT *
FROM customers
ORDER BY city ASC, first_name ASC;""")

    customer_id first_name last_name              email       phone       city
0             1      Akash    Sharma    akash1@mail.com  9666696518  Bangalore
1            11      Akash     Patel   akash11@mail.com  9719551111  Bangalore
2            16     Anjali     Singh  anjali16@mail.com  9118811611  Bangalore
3             2       Ritu       Das     ritu2@mail.com  9627404182  Bangalore
4            10      Aisha     Kumar   aisha10@mail.com  9332083015    Chennai
5            36     Anjali     Gupta  anjali36@mail.com  9310837702    Chennai
6            38      Komal       Roy   komal38@mail.com  9634822466    Chennai
7            39      Nitin       Das   nitin39@mail.com  9759424149    Chennai
8            32       Ritu    Sharma    ritu32@mail.com  9787498671    Chennai
9             4     Simran       Das   simran4@mail.com  9979444461    Chennai
10           20      Aisha     Kumar   aisha20@mail.com  9659589923      Delhi
11           26     Anjali     Kumar  anjali26@mail.com  9988357959      Delhi
12           27     Deepak    Sharma  deepak27@mail.com  9922832851      Delhi
13            8      Komal       Roy    komal8@mail.com  9467566361      Delhi
14           33      Mohit       Roy   mohit33@mail.com  9665152033      Delhi
15           12       Ritu     Kumar    ritu12@mail.com  9658448295      Delhi
16            7     Deepak    Wilson   deepak7@mail.com  9906274295  Hyderabad
17           17     Deepak    Taylor  deepak17@mail.com  9865412201  Hyderabad
18           13      Mohit       Das   mohit13@mail.com  9361812679  Hyderabad
19            9      Nitin     Brown    nitin9@mail.com  9899533704  Hyderabad
20           19      Nitin    Taylor   nitin19@mail.com  9995653703  Hyderabad
21           29      Nitin    Wilson   nitin29@mail.com  9200774016  Hyderabad
22           22       Ritu     Kumar    ritu22@mail.com  9882449902  Hyderabad
23           15       Yash    Sharma    yash15@mail.com  9702952921  Hyderabad
24           35       Yash       Das    yash35@mail.com  9847568100  Hyderabad
25           40      Aisha    Taylor   aisha40@mail.com  9829603810    Kolkata
26           31      Akash     Gupta   akash31@mail.com  9750806415    Kolkata
27           18      Komal     Singh   komal18@mail.com  9504584808    Kolkata
28           23      Mohit    Taylor   mohit23@mail.com  9744597750    Kolkata
29           14     Simran    Taylor  simran14@mail.com  9604314504    Kolkata
30           30      Aisha       Das   aisha30@mail.com  9627755893     Mumbai
31           28      Komal     Singh   komal28@mail.com  9110051432     Mumbai
32            3      Mohit     Kumar    mohit3@mail.com  9208428912     Mumbai
33           21      Akash    Sharma   akash21@mail.com  9124393190       Pune
34            6     Anjali     Singh   anjali6@mail.com  9693986973       Pune
35           37     Deepak    Wilson  deepak37@mail.com  9413891625       Pune
36           24     Simran       Das  simran24@mail.com  9185583902       Pune
37           34     Simran    Wilson  simran34@mail.com  9642604350       Pune
38            5       Yash    Sharma     yash5@mail.com  9426111115       Pune
39           25       Yash     Singh    yash25@mail.com  9834197053       Pune

In [12]:
#4
run_sql("""SELECT *
FROM orders
ORDER BY customer_id ASC, order_date ASC;""")

    order_id  customer_id  product_id  order_date  quantity
0         10            1          10  2024-07-16         5
1          7            2          20  2024-05-15         2
2         66            2           3  2024-08-03         4
3         52            2          23  2026-01-31         4
4         80            3           6  2024-01-26         2
..       ...          ...         ...         ...       ...
95        34           35          11  2024-01-12         4
96        47           35          14  2024-07-22         4
97        98           35           8  2025-02-24         2
98        40           35          10  2025-07-24         1
99        25           35          23  2025-12-12         5

[100 rows x 5 columns]

In [13]:
#5
run_sql("""SELECT *
FROM employees
ORDER BY department_id ASC, first_name ASC;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
1,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
2,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com
3,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
4,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
5,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
6,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
7,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com
8,13,Liam,Singh,3,2020-10-03,105000.0,Software Engineer,Mumbai,liam.singh13@company.com
9,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
10,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
11,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
12,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com
13,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
14,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com
15,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
16,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
17,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
18,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com
19,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
20,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
21,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
22,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com
23,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
24,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com
25,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com
26,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com
27,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com
28,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com
29,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com

In [14]:
# Bonus Challege
run_sql("""SELECT *
FROM employees
ORDER BY department_id ASC, salary DESC;""")

,employee_id,first_name,last_name,department_id,hire_date,salary,job_title,city,email
0,11,Noah,Singh,1,2023-04-11,112500.0,HR Executive,Delhi,noah.singh11@company.com
1,1,Aarav,Patel,1,2020-07-10,47500.0,HR Executive,Chennai,aarav.patel1@company.com
2,21,Arjun,Taylor,1,2021-09-03,42500.0,HR Executive,Bangalore,arjun.taylor21@company.com
3,2,Vivaan,Patel,2,2022-01-10,105000.0,Accountant,Bangalore,vivaan.patel2@company.com
4,22,Isha,Roy,2,2022-08-14,60000.0,Accountant,Hyderabad,isha.roy22@company.com
5,12,Olivia,Roy,2,2021-02-05,50000.0,Accountant,Bangalore,olivia.roy12@company.com
6,13,Liam,Singh,3,2020-10-03,105000.0,Software Engineer,Mumbai,liam.singh13@company.com
7,23,Kabir,Sharma,3,2023-05-02,105000.0,Software Engineer,Mumbai,kabir.sharma23@company.com
8,3,Aditya,Das,3,2021-11-02,45000.0,Software Engineer,Delhi,aditya.das3@company.com
9,4,Riya,Das,4,2024-02-16,117500.0,Marketing Executive,Delhi,riya.das4@company.com
10,24,Meera,Singh,4,2021-07-03,112500.0,Marketing Executive,Hyderabad,meera.singh24@company.com
11,14,Sophia,Roy,4,2022-01-01,97500.0,Marketing Executive,Delhi,sophia.roy14@company.com
12,5,Priya,Das,5,2020-01-29,120000.0,Sales Executive,Mumbai,priya.das5@company.com
13,15,Ananya,Singh,5,2022-08-02,72500.0,Sales Executive,Kolkata,ananya.singh15@company.com
14,25,Vikram,Roy,5,2024-11-20,57500.0,Sales Executive,Pune,vikram.roy25@company.com
15,16,Karan,Taylor,6,2021-01-27,117500.0,Operations Analyst,Pune,karan.taylor16@company.com
16,26,Nisha,Sharma,6,2023-08-06,110000.0,Operations Analyst,Pune,nisha.sharma26@company.com
17,6,Neha,Taylor,6,2024-11-24,67500.0,Operations Analyst,Hyderabad,neha.taylor6@company.com
18,7,Rahul,Roy,7,2019-02-23,90000.0,Support Engineer,Mumbai,rahul.roy7@company.com
19,27,Daniel,Roy,7,2023-05-29,60000.0,Support Engineer,Pune,daniel.roy27@company.com
20,17,Rohan,Singh,7,2022-04-21,52500.0,Support Engineer,Mumbai,rohan.singh17@company.com
21,8,Amit,Roy,8,2021-05-07,105000.0,Legal Advisor,Bangalore,amit.roy8@company.com
22,18,Sneha,Sharma,8,2020-01-20,50000.0,Legal Advisor,Bangalore,sneha.sharma18@company.com
23,28,Grace,Brown,8,2023-03-29,40000.0,Legal Advisor,Bangalore,grace.brown28@company.com
24,29,Aryan,Das,9,2022-12-19,70000.0,Data Engineer,Hyderabad,aryan.das29@company.com
25,19,David,Singh,9,2021-04-21,62500.0,Data Engineer,Pune,david.singh19@company.com
26,9,John,Brown,9,2021-11-22,45000.0,Data Engineer,Pune,john.brown9@company.com
27,30,Pooja,Sharma,10,2020-05-02,120000.0,Security Analyst,Pune,pooja.sharma30@company.com
28,10,Emma,Kumar,10,2023-07-25,97500.0,Security Analyst,Kolkata,emma.kumar10@company.com
29,20,Sara,Taylor,10,2023-12-21,85000.0,Security Analyst,Delhi,sara.taylor20@company.com