<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day050sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [1]:
# INNER JOIN - Final Practice

In [7]:
#1 Display each employee along with the department name.
run_sql("""SELECT e.first_name, e.last_name, d.department_name
FROM employees e
INNER JOIN departments d
ON e.department_id = d.department_id;""")

   first_name last_name   department_name
0       Aarav     Patel                HR
1      Vivaan     Patel           Finance
2      Aditya       Das                IT
3        Riya       Das         Marketing
4       Priya       Das             Sales
5        Neha    Taylor        Operations
6       Rahul       Roy           Support
7        Amit       Roy             Legal
8        John     Brown  Data Engineering
9        Emma     Kumar          Security
10       Noah     Singh                HR
11     Olivia       Roy           Finance
12       Liam     Singh                IT
13     Sophia       Roy         Marketing
14     Ananya     Singh             Sales
15      Karan    Taylor        Operations
16      Rohan     Singh           Support
17      Sneha    Sharma             Legal
18      David     Singh  Data Engineering
19       Sara    Taylor          Security
20      Arjun    Taylor                HR
21       Isha       Roy           Finance
22      Kabir    Sharma                IT
23      Meera     Singh         Marketing
24     Vikram       Roy             Sales
25      Nisha    Sharma        Operations
26     Daniel       Roy           Support
27      Grace     Brown             Legal
28      Aryan       Das  Data Engineering
29      Pooja    Sharma          Security

In [10]:
#2 Display each order together with the customer name.
run_sql("""SELECT o.*, c.first_name, c.last_name
FROM orders o
INNER JOIN customers c
ON o.customer_id = c.customer_id;""")

,order_id,customer_id,product_id,order_date,quantity,first_name,last_name
0,1,20,2,2025-10-15,4,Aisha,Kumar
1,2,11,16,2025-02-26,2,Akash,Patel
2,3,29,24,2024-01-15,3,Nitin,Wilson
3,4,17,23,2024-09-08,5,Deepak,Taylor
4,5,16,3,2024-12-14,1,Anjali,Singh
...,...,...,...,...,...,...,...
95,96,24,8,2026-03-28,5,Simran,Das
96,97,32,11,2024-10-06,2,Ritu,Sharma
97,98,35,8,2025-02-24,2,Yash,Das
98,99,4,23,2024-09-19,1,Simran,Das
99,100,32,17,2024-07-13,5,Ritu,Sharma

In [12]:
#3 Display each order with the customer name and product name.
run_sql("""SELECT o.order_id,
          c.first_name,
          c.last_name,
          p.product_name
          FROM orders o
          INNER JOIN customers c
          ON o.customer_id = c.customer_id
          INNER JOIN products p
          ON o.product_id =p.product_id;""" )

    order_id first_name last_name        product_name
0          1      Aisha     Kumar      Laptop Model 2
1          2      Akash     Patel     Monitor Model 4
2          3      Nitin    Wilson       Mouse Model 4
3          4     Deepak    Taylor       Mouse Model 3
4          5     Anjali     Singh      Laptop Model 3
..       ...        ...       ...                 ...
95        96     Simran       Das      Mobile Model 4
96        97       Ritu    Sharma  Headphones Model 3
97        98       Yash       Das      Mobile Model 4
98        99     Simran       Das       Mouse Model 3
99       100       Ritu    Sharma    Keyboard Model 1

[100 rows x 4 columns]

In [13]:
#4 Display each supplier along with the products supplied by them.
# no supplier table

In [14]:
#5
run_sql("""SELECT c.customer_id,
           c.first_name,
           c.last_name,
           COUNT(DISTINCT o.order_id) AS total_orders,
           SUM(o.quantity) AS total_quantity
           FROM customers c
           INNER JOIN orders o
           ON c.customer_id = o.customer_id
           GROUP BY c.customer_id, c.first_name, c.last_name;""")

    customer_id first_name last_name  total_orders  total_quantity
0             1      Akash    Sharma             1               5
1             2       Ritu       Das             3              10
2             3      Mohit     Kumar             3               4
3             4     Simran       Das             3               7
4             5       Yash    Sharma             3              10
5             7     Deepak    Wilson             1               4
6             8      Komal       Roy             3               7
7             9      Nitin     Brown             4              17
8            10      Aisha     Kumar             2               7
9            11      Akash     Patel             3               6
10           12       Ritu     Kumar             1               2
11           13      Mohit       Das             6              16
12           14     Simran    Taylor             5              14
13           15       Yash    Sharma             5              17
14           16     Anjali     Singh             5              13
15           17     Deepak    Taylor             2               8
16           18      Komal     Singh             1               5
17           19      Nitin    Taylor             2               5
18           20      Aisha     Kumar             3              11
19           23      Mohit    Taylor             1               3
20           24     Simran       Das             3              15
21           25       Yash     Singh             3               9
22           26     Anjali     Kumar             4              10
23           27     Deepak    Sharma             2               5
24           28      Komal     Singh             3               5
25           29      Nitin    Wilson             3               9
26           30      Aisha       Das             2               9
27           31      Akash     Gupta             1               3
28           32       Ritu    Sharma             7              20
29           33      Mohit       Roy             2               2
30           34     Simran    Wilson             8              19
31           35       Yash       Das             5              16

In [25]:

# Bonus Challege.
run_sql("""SELECT d.department_id,
        d.department_name,
        COUNT(e.employee_id) AS number_of_employees
        FROM departments d
        INNER JOIN employees e
        ON d.department_id = e.department_id
        GROUP BY d.department_id, d.department_name;""")

   department_id   department_name  number_of_employees
0              1                HR                    3
1              2           Finance                    3
2              3                IT                    3
3              4         Marketing                    3
4              5             Sales                    3
5              6        Operations                    3
6              7           Support                    3
7              8             Legal                    3
8              9  Data Engineering                    3
9             10          Security                    3