<a href="https://colab.research.google.com/github/surbhi-codehub/100-Days-SQL-Journey/blob/main/day4sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [11]:
# 1
run_sql("""SELECT department_name
FROM departments;""")

    department_name
0                HR
1           Finance
2                IT
3         Marketing
4             Sales
5        Operations
6           Support
7             Legal
8  Data Engineering
9          Security

In [12]:
# 2
run_sql("""SELECT first_name, email
FROM employees;""")

   first_name                       email
0       Aarav    aarav.patel1@company.com
1      Vivaan   vivaan.patel2@company.com
2      Aditya     aditya.das3@company.com
3        Riya       riya.das4@company.com
4       Priya      priya.das5@company.com
5        Neha    neha.taylor6@company.com
6       Rahul      rahul.roy7@company.com
7        Amit       amit.roy8@company.com
8        John     john.brown9@company.com
9        Emma    emma.kumar10@company.com
10       Noah    noah.singh11@company.com
11     Olivia    olivia.roy12@company.com
12       Liam    liam.singh13@company.com
13     Sophia    sophia.roy14@company.com
14     Ananya  ananya.singh15@company.com
15      Karan  karan.taylor16@company.com
16      Rohan   rohan.singh17@company.com
17      Sneha  sneha.sharma18@company.com
18      David   david.singh19@company.com
19       Sara   sara.taylor20@company.com
20      Arjun  arjun.taylor21@company.com
21       Isha      isha.roy22@company.com
22      Kabir  kabir.sharma23@company.com
23      Meera   meera.singh24@company.com
24     Vikram    vikram.roy25@company.com
25      Nisha  nisha.sharma26@company.com
26     Daniel    daniel.roy27@company.com
27      Grace   grace.brown28@company.com
28      Aryan     aryan.das29@company.com
29      Pooja  pooja.sharma30@company.com

In [13]:
# 3
run_sql("""SELECT product_name, price
FROM products;""")

          product_name    price
0       Laptop Model 1  90499.0
1       Laptop Model 2  90999.0
2       Laptop Model 3  91499.0
3       Laptop Model 4  91999.0
4       Mobile Model 1  30499.0
5       Mobile Model 2  30999.0
6       Mobile Model 3  31499.0
7       Mobile Model 4  31999.0
8   Headphones Model 1   5499.0
9   Headphones Model 2   5999.0
10  Headphones Model 3   6499.0
11  Headphones Model 4   6999.0
12     Monitor Model 1  16499.0
13     Monitor Model 2  16999.0
14     Monitor Model 3  17499.0
15     Monitor Model 4  17999.0
16    Keyboard Model 1   2499.0
17    Keyboard Model 2   2999.0
18    Keyboard Model 3   3499.0
19    Keyboard Model 4   3999.0
20       Mouse Model 1   1499.0
21       Mouse Model 2   1999.0
22       Mouse Model 3   2499.0
23       Mouse Model 4   2999.0
24      Camera Model 1  46499.0

In [18]:
# 4
run_sql("""SELECT first_name, last_name, email
FROM customers;""")

   first_name last_name              email
0       Akash    Sharma    akash1@mail.com
1        Ritu       Das     ritu2@mail.com
2       Mohit     Kumar    mohit3@mail.com
3      Simran       Das   simran4@mail.com
4        Yash    Sharma     yash5@mail.com
5      Anjali     Singh   anjali6@mail.com
6      Deepak    Wilson   deepak7@mail.com
7       Komal       Roy    komal8@mail.com
8       Nitin     Brown    nitin9@mail.com
9       Aisha     Kumar   aisha10@mail.com
10      Akash     Patel   akash11@mail.com
11       Ritu     Kumar    ritu12@mail.com
12      Mohit       Das   mohit13@mail.com
13     Simran    Taylor  simran14@mail.com
14       Yash    Sharma    yash15@mail.com
15     Anjali     Singh  anjali16@mail.com
16     Deepak    Taylor  deepak17@mail.com
17      Komal     Singh   komal18@mail.com
18      Nitin    Taylor   nitin19@mail.com
19      Aisha     Kumar   aisha20@mail.com
20      Akash    Sharma   akash21@mail.com
21       Ritu     Kumar    ritu22@mail.com
22      Mohit    Taylor   mohit23@mail.com
23     Simran       Das  simran24@mail.com
24       Yash     Singh    yash25@mail.com
25     Anjali     Kumar  anjali26@mail.com
26     Deepak    Sharma  deepak27@mail.com
27      Komal     Singh   komal28@mail.com
28      Nitin    Wilson   nitin29@mail.com
29      Aisha       Das   aisha30@mail.com
30      Akash     Gupta   akash31@mail.com
31       Ritu    Sharma    ritu32@mail.com
32      Mohit       Roy   mohit33@mail.com
33     Simran    Wilson  simran34@mail.com
34       Yash       Das    yash35@mail.com
35     Anjali     Gupta  anjali36@mail.com
36     Deepak    Wilson  deepak37@mail.com
37      Komal       Roy   komal38@mail.com
38      Nitin       Das   nitin39@mail.com
39      Aisha    Taylor   aisha40@mail.com

In [19]:
# 5
run_sql("""SELECT order_id, customer_id, order_date
FROM orders;""")

    order_id  customer_id  order_date
0          1           20  2025-10-15
1          2           11  2025-02-26
2          3           29  2024-01-15
3          4           17  2024-09-08
4          5           16  2024-12-14
..       ...          ...         ...
95        96           24  2026-03-28
96        97           32  2024-10-06
97        98           35  2025-02-24
98        99            4  2024-09-19
99       100           32  2024-07-13

[100 rows x 3 columns]

In [20]:
# Bonus Challenge
# Display product_id ,product_name, and category from the products table.

run_sql("""SELECT product_id, product_name,category
FROM products;""")

    product_id        product_name    category
0            1      Laptop Model 1      Laptop
1            2      Laptop Model 2      Laptop
2            3      Laptop Model 3      Laptop
3            4      Laptop Model 4      Laptop
4            5      Mobile Model 1      Mobile
5            6      Mobile Model 2      Mobile
6            7      Mobile Model 3      Mobile
7            8      Mobile Model 4      Mobile
8            9  Headphones Model 1  Headphones
9           10  Headphones Model 2  Headphones
10          11  Headphones Model 3  Headphones
11          12  Headphones Model 4  Headphones
12          13     Monitor Model 1     Monitor
13          14     Monitor Model 2     Monitor
14          15     Monitor Model 3     Monitor
15          16     Monitor Model 4     Monitor
16          17    Keyboard Model 1    Keyboard
17          18    Keyboard Model 2    Keyboard
18          19    Keyboard Model 3    Keyboard
19          20    Keyboard Model 4    Keyboard
20          21       Mouse Model 1       Mouse
21          22       Mouse Model 2       Mouse
22          23       Mouse Model 3       Mouse
23          24       Mouse Model 4       Mouse
24          25      Camera Model 1      Camera