<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day043sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Learn how to filter grouped result after using GROUP BY.

In [14]:
#1 Display each department_id and the number of employees. Show only department that have more than 2 employees.
run_sql("""SELECT department_id, COUNT(*) AS employee_count
FROM employees
GROUP BY department_id
HAVING COUNT(*) > 2;""")

   department_id  employee_count
0              1               3
1              2               3
2              3               3
3              4               3
4              5               3
5              6               3
6              7               3
7              8               3
8              9               3
9             10               3

In [6]:
#2 Display each product category and the total number of products. Show only categories with more than 5 products.
run_sql("""SELECT category, COUNT(*) AS product_count
FROM products
GROUP BY category
HAVING COUNT(*) > 5;""")

Empty DataFrame
Columns: [category, product_count]
Index: []

In [7]:
#3 Display each customer and the total number of orders. Show only customer who place more than 1 order.
run_sql("""SELECT customer_id, COUNT(*) AS  order_count
FROM orders
GROUP BY customer_id
HAVING COUNT(*) > 1;""")

    customer_id  order_count
0             2            3
1             3            3
2             4            3
3             5            3
4             8            3
5             9            4
6            10            2
7            11            3
8            13            6
9            14            5
10           15            5
11           16            5
12           17            2
13           19            2
14           20            3
15           24            3
16           25            3
17           26            4
18           27            2
19           28            3
20           29            3
21           30            2
22           32            7
23           33            2
24           34            8
25           35            5

In [9]:
#4 Display each department _id and  the average salary. Show only department where the average salary is greater than 50000.
run_sql("""SELECT department_id, AVG(salary) AS average_salary
FROM employees
GROUP BY department_id
HAVING AVG(salary) > 5000;""")

   department_id  average_salary
0              1    67500.000000
1              2    71666.666667
2              3    85000.000000
3              4   109166.666667
4              5    83333.333333
5              6    98333.333333
6              7    67500.000000
7              8    65000.000000
8              9    59166.666667
9             10   100833.333333

In [10]:
#5 Dispaly each product category with total stock quantity.Show only categories where the total stock quantity than 100.
run_sql("""SELECT category, SUM(stock_quantity) AS total_stock
FROM products
GROUP BY category
HAVING SUM(stock_quantity) > 100;""")

     category  total_stock
0  Headphones          165
1    Keyboard          170

In [13]:
# Bonus Challege
run_sql("""SELECT customer_id, SUM(quantity) AS total_ordered_quantity
FROM orders
GROUP BY customer_id
HAVING SUM(quantity) > 10;""")

   customer_id  total_ordered_quantity
0            9                      17
1           13                      16
2           14                      14
3           15                      17
4           16                      13
5           20                      11
6           24                      15
7           32                      20
8           34                      19
9           35                      16