<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day045.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: GROUP BY & HAVING - Practice Day

In [3]:
#1.
run_sql("""SELECT department_id, COUNT(*) AS  total_employees
FROM  employees
GROUP BY department_id
HAVING COUNT(*) >= 2;""")

   department_id  total_employees
0              1                3
1              2                3
2              3                3
3              4                3
4              5                3
5              6                3
6              7                3
7              8                3
8              9                3
9             10                3

In [5]:
#2.
run_sql("""SELECT category, COUNT(*) AS total_products
FROM products
WHERE price > 500
GROUP BY category
HAVING COUNT(*) > 2;""")

     category  total_products
0  Headphones               4
1    Keyboard               4
2      Laptop               4
3      Mobile               4
4     Monitor               4
5       Mouse               4

In [6]:
#3.
run_sql("""SELECT customer_id, SUM(quantity) AS total_quantity
FROM orders
WHERE quantity >= 2
GROUP BY customer_id
HAVING SUM(quantity) >= 8;""")

    customer_id  total_quantity
0             2              10
1             5              10
2             9              17
3            13              15
4            14              12
5            15              17
6            16              12
7            17               8
8            20              11
9            24              15
10           25               9
11           26               9
12           29               8
13           30               9
14           32              18
15           34              15
16           35              15

In [8]:
#4.
run_sql("""SELECT department_id, AVG(salary) AS average_salary
FROM employees
WHERE salary > 40000
GROUP BY department_id
HAVING AVG(salary) > 60000;""")

   department_id  average_salary
0              1    67500.000000
1              2    71666.666667
2              3    85000.000000
3              4   109166.666667
4              5    83333.333333
5              6    98333.333333
6              7    67500.000000
7              8    77500.000000
8             10   100833.333333

In [9]:
#5.
run_sql("""SELECT category, SUM(stock_quantity) AS total_stock
FROM products
WHERE price > 1000
GROUP BY category
HAVING SUM(stock_quantity) > 150;""")

     category  total_stock
0  Headphones          165
1    Keyboard          170

In [12]:
# Bonus Challenge
run_sql("""SELECT customer_id,
        COUNT(*) AS total_orders,
        MAX(quantity) AS maximum_order_quantity
        FROM orders
        GROUP BY customer_id
        HAVING COUNT(*) > 1;""")

    customer_id  total_orders  maximum_order_quantity
0             2             3                       4
1             3             3                       2
2             4             3                       3
3             5             3                       4
4             8             3                       4
5             9             4                       5
6            10             2                       4
7            11             3                       2
8            13             6                       5
9            14             5                       5
10           15             5                       5
11           16             5                       5
12           17             2                       5
13           19             2                       4
14           20             3                       5
15           24             3                       5
16           25             3                       4
17           26             4                       4
18           27             2                       3
19           28             3                       3
20           29             3                       5
21           30             2                       5
22           32             7                       5
23           33             2                       1
24           34             8                       5
25           35             5                       5