<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day044sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Combining WHERE, GROUP BY, and HAVING.

In [3]:
# 1.
run_sql("""SELECT department_id, COUNT(*) AS total_employees
FROM employees
WHERE salary > 30000
GROUP BY department_id
HAVING COUNT(*) > 2;""")

   department_id  total_employees
0              1                3
1              2                3
2              3                3
3              4                3
4              5                3
5              6                3
6              7                3
7              8                3
8              9                3
9             10                3

In [4]:
# 2
run_sql("""SELECT category, AVG(price) AS average_price
FROM products
WHERE stock_quantity > 10
GROUP BY category
HAVING AVG(price) > 1000;""")

     category  average_price
0  Headphones    5999.000000
1    Keyboard    3165.666667
2      Laptop   90999.000000
3      Mobile   30999.000000
4     Monitor   17249.000000
5       Mouse    2249.000000

In [5]:
# 3.
run_sql("""SELECT customer_id, SUM(quantity) AS total_quantity
FROM orders
WHERE quantity > 1
GROUP BY customer_id
HAVING SUM(quantity) > 5;""")

    customer_id  total_quantity
0             2              10
1             4               6
2             5              10
3             8               6
4             9              17
5            10               7
6            11               6
7            13              15
8            14              12
9            15              17
10           16              12
11           17               8
12           20              11
13           24              15
14           25               9
15           26               9
16           29               8
17           30               9
18           32              18
19           34              15
20           35              15

In [8]:
# 4.
run_sql("""SELECT department_id, MAX(salary) AS maximum_salary
FROM employees
WHERE hire_date > '2022-01-01'
GROUP BY department_id
HAVING MAX(salary) > 70000;""")

   department_id  maximum_salary
0              1        112500.0
1              2        105000.0
2              3        105000.0
3              4        117500.0
4              5         72500.0
5              6        110000.0
6             10         97500.0

In [9]:
# 5.
run_sql("""SELECT category, SUM(stock_quantity) AS total_stock
FROM products
WHERE price > 500
GROUP BY category
HAVING SUM(stock_quantity) > 100;""")

     category  total_stock
0  Headphones          165
1    Keyboard          170

In [11]:
# Bonus Challenge
run_sql("""SELECT customer_id, COUNT(*) AS total_orders
        FROM orders
        WHERE order_date > '2023-01-01'
        GROUP BY customer_id
        HAVING COUNT(*) > 1;""")

    customer_id  total_orders
0             2             3
1             3             3
2             4             3
3             5             3
4             8             3
5             9             4
6            10             2
7            11             3
8            13             6
9            14             5
10           15             5
11           16             5
12           17             2
13           19             2
14           20             3
15           24             3
16           25             3
17           26             4
18           27             2
19           28             3
20           29             3
21           30             2
22           32             7
23           33             2
24           34             8
25           35             5