<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day053sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [2]:
# Topic: Left JOIN - Practical Reports

In [4]:
#1.
run_sql("""SELECT
c.customer_id,
c.first_name,
c.last_name,
COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name;""")

    customer_id first_name last_name  total_orders
0             1      Akash    Sharma             1
1             2       Ritu       Das             3
2             3      Mohit     Kumar             3
3             4     Simran       Das             3
4             5       Yash    Sharma             3
5             6     Anjali     Singh             0
6             7     Deepak    Wilson             1
7             8      Komal       Roy             3
8             9      Nitin     Brown             4
9            10      Aisha     Kumar             2
10           11      Akash     Patel             3
11           12       Ritu     Kumar             1
12           13      Mohit       Das             6
13           14     Simran    Taylor             5
14           15       Yash    Sharma             5
15           16     Anjali     Singh             5
16           17     Deepak    Taylor             2
17           18      Komal     Singh             1
18           19      Nitin    Taylor             2
19           20      Aisha     Kumar             3
20           21      Akash    Sharma             0
21           22       Ritu     Kumar             0
22           23      Mohit    Taylor             1
23           24     Simran       Das             3
24           25       Yash     Singh             3
25           26     Anjali     Kumar             4
26           27     Deepak    Sharma             2
27           28      Komal     Singh             3
28           29      Nitin    Wilson             3
29           30      Aisha       Das             2
30           31      Akash     Gupta             1
31           32       Ritu    Sharma             7
32           33      Mohit       Roy             2
33           34     Simran    Wilson             8
34           35       Yash       Das             5
35           36     Anjali     Gupta             0
36           37     Deepak    Wilson             0
37           38      Komal       Roy             0
38           39      Nitin       Das             0
39           40      Aisha    Taylor             0

In [7]:
#2.
run_sql("""SELECT
          d.department_id,
          d.department_name,
          AVG(e.salary) AS average_salary
          FROM departments d
          LEFT JOIN employees e
           ON d.department_id = e.department_id
          GROUP BY d.department_id, d.department_name;""")

   department_id   department_name  average_salary
0              1                HR    67500.000000
1              2           Finance    71666.666667
2              3                IT    85000.000000
3              4         Marketing   109166.666667
4              5             Sales    83333.333333
5              6        Operations    98333.333333
6              7           Support    67500.000000
7              8             Legal    65000.000000
8              9  Data Engineering    59166.666667
9             10          Security   100833.333333

In [8]:
#3.
# no supplier table

In [31]:
#4.
run_sql("""SELECT
    p.product_id,
    p.product_name,
    COALESCE(SUM(o.quantity), 0) AS total_quantity_ordered
FROM products p
LEFT JOIN orders o
    ON p.product_id = o.product_id
GROUP BY p.product_id, p.product_name;""")

    product_id        product_name  total_quantity_ordered
0            1      Laptop Model 1                      22
1            2      Laptop Model 2                      12
2            3      Laptop Model 3                      16
3            4      Laptop Model 4                      13
4            5      Mobile Model 1                       5
5            6      Mobile Model 2                       6
6            7      Mobile Model 3                       1
7            8      Mobile Model 4                      27
8            9  Headphones Model 1                       5
9           10  Headphones Model 2                      12
10          11  Headphones Model 3                       8
11          12  Headphones Model 4                       6
12          13     Monitor Model 1                       5
13          14     Monitor Model 2                      11
14          15     Monitor Model 3                       8
15          16     Monitor Model 4                      17
16          17    Keyboard Model 1                      13
17          18    Keyboard Model 2                       6
18          19    Keyboard Model 3                      13
19          20    Keyboard Model 4                      24
20          21       Mouse Model 1                      16
21          22       Mouse Model 2                       9
22          23       Mouse Model 3                      23
23          24       Mouse Model 4                      10
24          25      Camera Model 1                       5

In [26]:
#5.
run_sql("""SELECT
 c.customer_id,
 c.first_name,
 COUNT(DISTINCT o.order_id ) AS total_orders,
 COALESCE(SUM(o.quantity), 0) AS total_quantity_ordered
 FROM customers c
 LEFT JOIN orders o
 ON o.customer_id = o.customer_id
 GROUP BY c.customer_id, c.first_name, c.last_name;""")

    customer_id first_name  total_orders  total_quantity_ordered
0             1      Akash           100                     293
1             2       Ritu           100                     293
2             3      Mohit           100                     293
3             4     Simran           100                     293
4             5       Yash           100                     293
5             6     Anjali           100                     293
6             7     Deepak           100                     293
7             8      Komal           100                     293
8             9      Nitin           100                     293
9            10      Aisha           100                     293
10           11      Akash           100                     293
11           12       Ritu           100                     293
12           13      Mohit           100                     293
13           14     Simran           100                     293
14           15       Yash           100                     293
15           16     Anjali           100                     293
16           17     Deepak           100                     293
17           18      Komal           100                     293
18           19      Nitin           100                     293
19           20      Aisha           100                     293
20           21      Akash           100                     293
21           22       Ritu           100                     293
22           23      Mohit           100                     293
23           24     Simran           100                     293
24           25       Yash           100                     293
25           26     Anjali           100                     293
26           27     Deepak           100                     293
27           28      Komal           100                     293
28           29      Nitin           100                     293
29           30      Aisha           100                     293
30           31      Akash           100                     293
31           32       Ritu           100                     293
32           33      Mohit           100                     293
33           34     Simran           100                     293
34           35       Yash           100                     293
35           36     Anjali           100                     293
36           37     Deepak           100                     293
37           38      Komal           100                     293
38           39      Nitin           100                     293
39           40      Aisha           100                     293

In [21]:
# Bonus Challenge
run_sql("""SELECT
d.department_id,
d.department_name,
MAX(e.salary) AS highest_salary
FROM departments d
LEFT JOIN employees e
ON d.department_id = e.department_id
GROUP BY d.department_id, d.department_name;""")

   department_id   department_name  highest_salary
0              1                HR        112500.0
1              2           Finance        105000.0
2              3                IT        105000.0
3              4         Marketing        117500.0
4              5             Sales        120000.0
5              6        Operations        117500.0
6              7           Support         90000.0
7              8             Legal        105000.0
8              9  Data Engineering         70000.0
9             10          Security        120000.0