<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day042sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [1]:
# Topic: GROUP BY Multiple Aggregate Functions.

In [16]:
# 1. Display each dapartment_id along with the total number of employees.
run_sql("""SELECT department_id, COUNT(*) AS total_employees
          FROM employees
          GROUP BY department_id;""")

   department_id  total_employees
0              1                3
1              2                3
2              3                3
3              4                3
4              5                3
5              6                3
6              7                3
7              8                3
8              9                3
9             10                3

In [17]:
# 2. Display each product category along with the number of products and the average product price.
run_sql("""SELECT category,
         count(*) AS total_products,
         AVG(price) AS average_price
         FROM products
         GROUP BY category;""")

     category  total_products  average_price
0      Camera               1        46499.0
1  Headphones               4         6249.0
2    Keyboard               4         3249.0
3      Laptop               4        91249.0
4      Mobile               4        31249.0
5     Monitor               4        17249.0
6       Mouse               4         2249.0

In [19]:
# 3. Display each customer along with the total number of orders and the total orders and the total ordered quantity.
run_sql("""SELECT c.customer_id,
            COUNT(o.order_id) AS total_orders,
            SUM(o.quantity) AS total_ordered_quantity
            FROM customers c
            LEFT JOIN orders o
            ON c.customer_id = o.customer_id
            GROUP BY c.customer_id;""")

    customer_id  total_orders  total_ordered_quantity
0             1             1                     5.0
1             2             3                    10.0
2             3             3                     4.0
3             4             3                     7.0
4             5             3                    10.0
5             6             0                     NaN
6             7             1                     4.0
7             8             3                     7.0
8             9             4                    17.0
9            10             2                     7.0
10           11             3                     6.0
11           12             1                     2.0
12           13             6                    16.0
13           14             5                    14.0
14           15             5                    17.0
15           16             5                    13.0
16           17             2                     8.0
17           18             1                     5.0
18           19             2                     5.0
19           20             3                    11.0
20           21             0                     NaN
21           22             0                     NaN
22           23             1                     3.0
23           24             3                    15.0
24           25             3                     9.0
25           26             4                    10.0
26           27             2                     5.0
27           28             3                     5.0
28           29             3                     9.0
29           30             2                     9.0
30           31             1                     3.0
31           32             7                    20.0
32           33             2                     2.0
33           34             8                    19.0
34           35             5                    16.0
35           36             0                     NaN
36           37             0                     NaN
37           38             0                     NaN
38           39             0                     NaN
39           40             0                     NaN

In [21]:
# 4. Display each  department_id with the minimum salary, maximum salary, and average salary.
run_sql("""SELECT department_id,
        MIN(salary) AS minimum_salary,
        MAX(salary) AS maximum_salary,
        AVG(salary) AS average_salary
        FROM employees
        GROUP BY department_id;""")

   department_id  minimum_salary  maximum_salary  average_salary
0              1         42500.0        112500.0    67500.000000
1              2         50000.0        105000.0    71666.666667
2              3         45000.0        105000.0    85000.000000
3              4         97500.0        117500.0   109166.666667
4              5         57500.0        120000.0    83333.333333
5              6         67500.0        117500.0    98333.333333
6              7         52500.0         90000.0    67500.000000
7              8         40000.0        105000.0    65000.000000
8              9         45000.0         70000.0    59166.666667
9             10         85000.0        120000.0   100833.333333

In [24]:
# 5. Display each product category with the total stock quantity, average product price, lowest price, and highest price.
run_sql(("""SELECT category,
SUM(stock_quantity) AS total_stock_qunatity,
AVG(price) AS average_product_price,
MIN(price) AS lowest_price,
MAX(price) AS highest_price
FROM products
GROUP BY category;"""))

,category,total_stock_qunatity,average_product_price,lowest_price,highest_price
0,Camera,0,46499.0,46499.0,46499.0
1,Headphones,165,6249.0,5499.0,6999.0
2,Keyboard,170,3249.0,2499.0,3999.0
3,Laptop,90,91249.0,90499.0,91999.0
4,Mobile,47,31249.0,30499.0,31999.0
5,Monitor,45,17249.0,16499.0,17999.0
6,Mouse,55,2249.0,1499.0,2999.0

In [26]:
# Bonus Challege
run_sql("""SELECT customer_id,
        MIN(quantity) AS minimum_order_quantity,
        MAX(quantity) AS maximum_order_quantity
        FROM orders
        GROUP BY customer_id;""")

    customer_id  minimum_order_quantity  maximum_order_quantity
0             1                       5                       5
1             2                       2                       4
2             3                       1                       2
3             4                       1                       3
4             5                       2                       4
5             7                       4                       4
6             8                       1                       4
7             9                       3                       5
8            10                       3                       4
9            11                       2                       2
10           12                       2                       2
11           13                       1                       5
12           14                       1                       5
13           15                       2                       5
14           16                       1                       5
15           17                       3                       5
16           18                       5                       5
17           19                       1                       4
18           20                       2                       5
19           23                       3                       3
20           24                       5                       5
21           25                       2                       4
22           26                       1                       4
23           27                       2                       3
24           28                       1                       3
25           29                       1                       5
26           30                       4                       5
27           31                       3                       3
28           32                       1                       5
29           33                       1                       1
30           34                       1                       5
31           35                       1                       5