<a href="https://colab.research.google.com/github/surbhi-codehub/100-days-sql/blob/main/day048sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [ ]:
# Topic: Introduction

In [ ]:
#1
run_sql("""SELECT
          employees.first_name,
          employees.last_name,
          departments.department_name
          FROM employees
          JOIN departments
          ON employees.department_id = departments.department_id;""")

   first_name last_name   department_name
0       Aarav     Patel                HR
1      Vivaan     Patel           Finance
2      Aditya       Das                IT
3        Riya       Das         Marketing
4       Priya       Das             Sales
5        Neha    Taylor        Operations
6       Rahul       Roy           Support
7        Amit       Roy             Legal
8        John     Brown  Data Engineering
9        Emma     Kumar          Security
10       Noah     Singh                HR
11     Olivia       Roy           Finance
12       Liam     Singh                IT
13     Sophia       Roy         Marketing
14     Ananya     Singh             Sales
15      Karan    Taylor        Operations
16      Rohan     Singh           Support
17      Sneha    Sharma             Legal
18      David     Singh  Data Engineering
19       Sara    Taylor          Security
20      Arjun    Taylor                HR
21       Isha       Roy           Finance
22      Kabir    Sharma                IT
23      Meera     Singh         Marketing
24     Vikram       Roy             Sales
25      Nisha    Sharma        Operations
26     Daniel       Roy           Support
27      Grace     Brown             Legal
28      Aryan       Das  Data Engineering
29      Pooja    Sharma          Security

In [ ]:
#2 Display each order along with customer name.
run_sql("""SELECT
        orders.order_id,
        customers.first_name,
        customers.last_name
        FROM orders
        JOIN customers
        ON orders.customer_id = customers.customer_id;""")

    order_id first_name last_name
0          1      Aisha     Kumar
1          2      Akash     Patel
2          3      Nitin    Wilson
3          4     Deepak    Taylor
4          5     Anjali     Singh
..       ...        ...       ...
95        96     Simran       Das
96        97       Ritu    Sharma
97        98       Yash       Das
98        99     Simran       Das
99       100       Ritu    Sharma

[100 rows x 3 columns]

In [22]:
#3
run_sql("""SELECT
    product_id,
    product_name,
    category,
    price
    FROM products;""")

    product_id        product_name    category    price
0            1      Laptop Model 1      Laptop  90499.0
1            2      Laptop Model 2      Laptop  90999.0
2            3      Laptop Model 3      Laptop  91499.0
3            4      Laptop Model 4      Laptop  91999.0
4            5      Mobile Model 1      Mobile  30499.0
5            6      Mobile Model 2      Mobile  30999.0
6            7      Mobile Model 3      Mobile  31499.0
7            8      Mobile Model 4      Mobile  31999.0
8            9  Headphones Model 1  Headphones   5499.0
9           10  Headphones Model 2  Headphones   5999.0
10          11  Headphones Model 3  Headphones   6499.0
11          12  Headphones Model 4  Headphones   6999.0
12          13     Monitor Model 1     Monitor  16499.0
13          14     Monitor Model 2     Monitor  16999.0
14          15     Monitor Model 3     Monitor  17499.0
15          16     Monitor Model 4     Monitor  17999.0
16          17    Keyboard Model 1    Keyboard   2499.0
17          18    Keyboard Model 2    Keyboard   2999.0
18          19    Keyboard Model 3    Keyboard   3499.0
19          20    Keyboard Model 4    Keyboard   3999.0
20          21       Mouse Model 1       Mouse   1499.0
21          22       Mouse Model 2       Mouse   1999.0
22          23       Mouse Model 3       Mouse   2499.0
23          24       Mouse Model 4       Mouse   2999.0
24          25      Camera Model 1      Camera  46499.0

In [ ]:
#4
run_sql("""SELECT
       orders.order_id,
       customers.first_name,
       customers.last_name,
       products.product_name
       FROM orders
       JOIN customers
       ON orders.customer_id = customers.customer_id
       JOIN products
       ON orders.product_id = products.product_id;""")

    order_id first_name last_name        product_name
0          1      Aisha     Kumar      Laptop Model 2
1          2      Akash     Patel     Monitor Model 4
2          3      Nitin    Wilson       Mouse Model 4
3          4     Deepak    Taylor       Mouse Model 3
4          5     Anjali     Singh      Laptop Model 3
..       ...        ...       ...                 ...
95        96     Simran       Das      Mobile Model 4
96        97       Ritu    Sharma  Headphones Model 3
97        98       Yash       Das      Mobile Model 4
98        99     Simran       Das       Mouse Model 3
99       100       Ritu    Sharma    Keyboard Model 1

[100 rows x 4 columns]

In [ ]:
#5
run_sql("""SELECT
        employees.first_name,
        employees.last_name,
        departments.department_name,
        departments.location
        FROM employees
        LEFT JOIN departments
        ON employees.department_id = departments.department_id;""")

   first_name last_name   department_name   location
0       Aarav     Patel                HR  Bangalore
1      Vivaan     Patel           Finance     Mumbai
2      Aditya       Das                IT  Bangalore
3        Riya       Das         Marketing      Delhi
4       Priya       Das             Sales  Hyderabad
5        Neha    Taylor        Operations       Pune
6       Rahul       Roy           Support    Chennai
7        Amit       Roy             Legal      Delhi
8        John     Brown  Data Engineering  Bangalore
9        Emma     Kumar          Security    Kolkata
10       Noah     Singh                HR  Bangalore
11     Olivia       Roy           Finance     Mumbai
12       Liam     Singh                IT  Bangalore
13     Sophia       Roy         Marketing      Delhi
14     Ananya     Singh             Sales  Hyderabad
15      Karan    Taylor        Operations       Pune
16      Rohan     Singh           Support    Chennai
17      Sneha    Sharma             Legal      Delhi
18      David     Singh  Data Engineering  Bangalore
19       Sara    Taylor          Security    Kolkata
20      Arjun    Taylor                HR  Bangalore
21       Isha       Roy           Finance     Mumbai
22      Kabir    Sharma                IT  Bangalore
23      Meera     Singh         Marketing      Delhi
24     Vikram       Roy             Sales  Hyderabad
25      Nisha    Sharma        Operations       Pune
26     Daniel       Roy           Support    Chennai
27      Grace     Brown             Legal      Delhi
28      Aryan       Das  Data Engineering  Bangalore
29      Pooja    Sharma          Security    Kolkata

In [ ]:
# Bonus Challenge
run_sql("""SELECT
       customers.customer_id,
       customers.first_name,
       customers.last_name,
       COUNT(orders.order_id) AS total_orders
       FROM customers

       INNER JOIN orders
       ON customers.customer_id = orders.customer_id
       GROUP BY
       customers.customer_id,
       customers.first_name,
       customers.last_name;""")

    customer_id first_name last_name  total_orders
0             1      Akash    Sharma             1
1             2       Ritu       Das             3
2             3      Mohit     Kumar             3
3             4     Simran       Das             3
4             5       Yash    Sharma             3
5             7     Deepak    Wilson             1
6             8      Komal       Roy             3
7             9      Nitin     Brown             4
8            10      Aisha     Kumar             2
9            11      Akash     Patel             3
10           12       Ritu     Kumar             1
11           13      Mohit       Das             6
12           14     Simran    Taylor             5
13           15       Yash    Sharma             5
14           16     Anjali     Singh             5
15           17     Deepak    Taylor             2
16           18      Komal     Singh             1
17           19      Nitin    Taylor             2
18           20      Aisha     Kumar             3
19           23      Mohit    Taylor             1
20           24     Simran       Das             3
21           25       Yash     Singh             3
22           26     Anjali     Kumar             4
23           27     Deepak    Sharma             2
24           28      Komal     Singh             3
25           29      Nitin    Wilson             3
26           30      Aisha       Das             2
27           31      Akash     Gupta             1
28           32       Ritu    Sharma             7
29           33      Mohit       Roy             2
30           34     Simran    Wilson             8
31           35       Yash       Das             5