<a href="https://colab.research.google.com/github/surbhi-codehub/100-Days-SQL-Journey/blob/main/day3sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect('/content/company.db')

# Helper function to run SQL queries
def run_sql(query):
    return pd.read_sql_query(query, conn)

print("✅ Connected to company.db successfully!")

✅ Connected to company.db successfully!

In [3]:
run_sql("""SELECT first_name
FROM employees;""")

   first_name
0       Aarav
1      Vivaan
2      Aditya
3        Riya
4       Priya
5        Neha
6       Rahul
7        Amit
8        John
9        Emma
10       Noah
11     Olivia
12       Liam
13     Sophia
14     Ananya
15      Karan
16      Rohan
17      Sneha
18      David
19       Sara
20      Arjun
21       Isha
22      Kabir
23      Meera
24     Vikram
25      Nisha
26     Daniel
27      Grace
28      Aryan
29      Pooja

In [4]:
run_sql("""SELECT department_name
FROM departments;""")

    department_name
0                HR
1           Finance
2                IT
3         Marketing
4             Sales
5        Operations
6           Support
7             Legal
8  Data Engineering
9          Security

In [6]:
run_sql("""SELECT product_name, price
FROM products;""")

          product_name    price
0       Laptop Model 1  90499.0
1       Laptop Model 2  90999.0
2       Laptop Model 3  91499.0
3       Laptop Model 4  91999.0
4       Mobile Model 1  30499.0
5       Mobile Model 2  30999.0
6       Mobile Model 3  31499.0
7       Mobile Model 4  31999.0
8   Headphones Model 1   5499.0
9   Headphones Model 2   5999.0
10  Headphones Model 3   6499.0
11  Headphones Model 4   6999.0
12     Monitor Model 1  16499.0
13     Monitor Model 2  16999.0
14     Monitor Model 3  17499.0
15     Monitor Model 4  17999.0
16    Keyboard Model 1   2499.0
17    Keyboard Model 2   2999.0
18    Keyboard Model 3   3499.0
19    Keyboard Model 4   3999.0
20       Mouse Model 1   1499.0
21       Mouse Model 2   1999.0
22       Mouse Model 3   2499.0
23       Mouse Model 4   2999.0
24      Camera Model 1  46499.0

In [26]:
run_sql("""PRAGMA table_info(customers);""")

   cid         name     type  notnull dflt_value  pk
0    0  customer_id  INTEGER        0       None   1
1    1   first_name     TEXT        0       None   0
2    2    last_name     TEXT        0       None   0
3    3        email     TEXT        0       None   0
4    4        phone     TEXT        0       None   0
5    5         city     TEXT        0       None   0

In [15]:
run_sql("""SELECT employee_id, first_name, salary
FROM employees;""")

    employee_id first_name    salary
0             1      Aarav   47500.0
1             2     Vivaan  105000.0
2             3     Aditya   45000.0
3             4       Riya  117500.0
4             5      Priya  120000.0
5             6       Neha   67500.0
6             7      Rahul   90000.0
7             8       Amit  105000.0
8             9       John   45000.0
9            10       Emma   97500.0
10           11       Noah  112500.0
11           12     Olivia   50000.0
12           13       Liam  105000.0
13           14     Sophia   97500.0
14           15     Ananya   72500.0
15           16      Karan  117500.0
16           17      Rohan   52500.0
17           18      Sneha   50000.0
18           19      David   62500.0
19           20       Sara   85000.0
20           21      Arjun   42500.0
21           22       Isha   60000.0
22           23      Kabir  105000.0
23           24      Meera  112500.0
24           25     Vikram   57500.0
25           26      Nisha  110000.0
26           27     Daniel   60000.0
27           28      Grace   40000.0
28           29      Aryan   70000.0
29           30      Pooja  120000.0